"""Personal-site content: the current editable source of truth."""
PAGES = [{'id': 'home',
  'path': '/',
  'title': 'Keir Dillon | Fractional CMO and founder of Dillon Agency',
  'description': 'Meet Keir Dillon: fractional CMO for wealth management firms, founder of Dillon '
                 'Agency, and a practical voice on brand strategy and advisor marketing.',
  'body': '<section class="editorial-hero personal-hero"><div class="hero-copy"><p '
          'class="kicker">Keir Dillon / Fractional CMO</p><h1>A clear point of view.<br><em>A '
          'habit of<br>building it.</em></h1><p class="hero-intro">I help wealth management '
          'leaders shape their brands and lead the marketing work through Dillon Agency. Here, I '
          'share the experience, questions, and practical tools behind that work.</p><a '
          'class="text-action" href="[[approach]]">Work with me <span '
          'aria-hidden="true">↗</span></a><div class="hero-signature"><span class="signature">Keir '
          'Dillon</span><span>Founder of Dillon Agency</span></div></div><div '
          'class="hero-image"><figure class="photo hero-photo"><img src="{{asset:keir-editorial}}" '
          'alt="Keir Dillon in an editorial portrait from his Esquire and Jim Beam archive" '
          'loading="eager" decoding="async" fetchpriority="high"></figure><div '
          'class="image-foot"><span>From the personal archive / Esquire × Jim Beam</span><span '
          'class="accent-line" aria-hidden="true"></span></div></div></section>\n'
          '<section class="intro-spread"><p class="margin-note">The work today</p><div><h2>Close '
          'to the leaders.<br><em>Close to the work.</em></h2></div><div class="intro-copy"><p>My '
          'role as a fractional CMO connects the firm’s brand, the marketing team, recruiting, and '
          'advisor support. I work alongside leadership and stay involved as decisions become '
          'execution.</p><p>Working directly with advisors keeps that perspective grounded in the '
          'people using the strategy.</p><a class="text-action" href="[[work]]">A view into the '
          'work <span aria-hidden="true">↗</span></a></div></section>\n'
          '<section class="selected-work"><div class="section-heading"><div><p class="kicker">The '
          'experience I bring</p><h2>Different chapters.<br><em>A connected '
          'perspective.</em></h2></div><p>Professional snowboarding. Live television. Building '
          'FRENDS and OPEN. Each chapter taught me something about understanding people and making '
          'an idea work in the world.</p></div><div class="work-duet"><figure class="photo '
          'product-metal"><img src="{{asset:frends-product}}" alt="FRENDS headphones with '
          'iridescent metal ear cups and a black leather headband" loading="lazy" '
          'decoding="async"><figcaption>FRENDS / From the founder '
          'archive</figcaption></figure><div class="work-story"><span '
          'class="work-name">FRENDS</span><h3>Know the person<br>you’re building for.</h3><p>As '
          'co-founder and CEO, I helped build a headphone brand around personal style and an '
          'audience whose preferences deserved attention.</p><p>That experience still shapes how I '
          'think about brand strategy, the team behind it, and the decisions that carry it '
          'forward.</p><a class="text-action" href="[[about]]">Read my story <span '
          'aria-hidden="true">↗</span></a></div></div></section>\n'
          '<section class="tool-workbench metal-surface"><div class="section-heading"><div><p '
          'class="kicker">For financial advisors</p><h2>A useful question.<br><em>A clearer next '
          'step.</em></h2></div><p>I share practical resources because helping advisors '
          'communicate is part of the work I care about. These tools are available at no cost and '
          'without registration.</p></div><div class="tool-list"><a class="tool-row" '
          'href="[[brief]]"><h3>The Positioning Blueprint</h3><p>Define the client, the situation, '
          'and a clearer introduction.</p><span class="arrow">↗</span></a><a class="tool-row" '
          'href="[[audit]]"><h3>The Sniff Test</h3><p>Review what someone can understand from your '
          'current presence.</p><span class="arrow">↗</span></a><a class="tool-row" '
          'href="[[planner]]"><h3>Client-question planner</h3><p>Turn one useful question into '
          'four content outlines.</p><span class="arrow">↗</span></a></div></section>\n'
          '<section class="notes-spread"><div class="notes-intro"><p class="kicker">Google '
          'Yourself / Field notes</p><h2>Show how you think.<br><em>Make it '
          'useful.</em></h2><p>Questions about positioning, presence, and the work behind a '
          'recognizable practice. Start with the written guides, and follow the developing series '
          'on LinkedIn.</p><a class="text-action" href="[[guides]]">Read the field notes <span '
          'aria-hidden="true">↗</span></a></div><div class="link-list"><a href="[[ideal]]">Who is '
          'your practice really for?<small>Define and test an ideal-client focus.</small></a><a '
          'href="[[referrals]]">What does a referral find?<small>Make your presence support the '
          'introduction.</small></a><a href="[[marketing]]">What belongs in your '
          'plan?<small>Connect the audience, message, and routine.</small></a></div></section>\n'
          '<section class="room-invitation"><div><p class="kicker">The Operator’s Room / Taking '
          'shape</p><h2>Good questions deserve<br><em>a working conversation.</em></h2><p>An '
          'advisor learning community in development around positioning, content, and practical '
          'marketing.</p></div><a class="button light-button" href="[[room]]">Explore The '
          'Room</a></section>\n'
          '<section class="simple-close metal-surface"><h2>Bring the question<br><em>you’re '
          'working on.</em></h2><div><p>A firm priority, an advisor question, a partnership, or an '
          'idea. Let’s start with a conversation.</p><a class="button" href="[[contact]]">Connect '
          'with Keir</a><p class="note spacer">For firm engagements, I work through <a '
          'href="{{peer:/}}">Dillon Agency</a>.</p></div></section>'},
 {'id': 'approach',
  'path': '/approach/',
  'title': 'Work with Keir Dillon | Fractional CMO',
  'description': 'Work with Keir Dillon as a fractional CMO through Dillon Agency. Brand '
                 'direction, marketing leadership, recruiting, and advisor support for wealth '
                 'management firms.',
  'body': '<section class="story-opening"><p class="kicker">Work with me</p><h1>Senior marketing '
          'leadership.<br><em>Personally involved.</em></h1><div class="story-opening-bottom"><p>I '
          'work with CEOs and firm leaders as a fractional CMO through Dillon Agency, connecting '
          'the brand, the people, and the work that needs to move forward.</p><span>Keir '
          'Dillon<br>Founder, Dillon Agency</span></div></section>\n'
          '<section class="engagement-spread"><div><h2>What I bring<br><em>to the '
          'table.</em></h2><p>A founder’s perspective, an eye for how a brand feels, and a '
          'practical interest in how the team delivers it.</p><p>My current work at Coastal Wealth '
          'spans brand strategy, marketing team leadership, recruiting strategy and '
          'implementation, and support for individual advisors.</p></div><div><h3>Where I tend to '
          'be most useful</h3><p>When the firm needs a clear direction for its marketing, someone '
          'to connect priorities across the business, and leadership that stays involved in '
          'delivery.</p><p>The right engagement starts with your context: the business you’re '
          'building, the team you have, and the decisions you need help owning.</p><a '
          'class="text-action" href="{{peer:/fractional-cmo/}}">Explore the role at Dillon Agency '
          '<span aria-hidden="true">↗</span></a></div></section>\n'
          '<section class="brand-relationship metal-surface"><div><p class="kicker">How the two '
          'connect</p><h2>You work with me.<br><em>The engagement lives<br>at Dillon '
          'Agency.</em></h2></div><div><p>This site is where I share my perspective, story, and '
          'advisor resources. Dillon Agency explains the services, engagement structure, and '
          'approach to delivering the work.</p><p>The team and partner support are defined around '
          'the scope. We agree on responsibilities before the work begins.</p><a '
          'class="text-action" href="{{peer:/approach/}}">See how the agency works <span '
          'aria-hidden="true">↗</span></a></div></section>\n'
          '<section class="simple-close"><h2>Start with<br><em>a '
          'conversation.</em></h2><div><p>You can contact me directly. Tell me what your firm is '
          'working toward and where you need help.</p><a class="button" href="[[contact]]">Talk '
          'with Keir</a></div></section>'},
 {'id': 'work',
  'path': '/selected-work/',
  'title': 'Selected work and perspective | Keir Dillon',
  'description': 'Keir Dillon’s contribution to firm marketing leadership and the founder '
                 'experience behind his approach. Explore the Coastal Wealth scope at Dillon '
                 'Agency.',
  'body': '<section class="story-opening"><p class="kicker">Selected work</p><h1>The '
          'decisions.<br>The responsibility.<br><em>What stays with you.</em></h1><div '
          'class="story-opening-bottom"><p>A few chapters that shape how I approach a firm’s '
          'brand, its people, and the practical work of building.</p><span>Current '
          'leadership<br>Founder experience</span></div></section>\n'
          '<section class="firm-record"><div class="firm-record-intro"><p class="kicker">Current '
          'work / Coastal Wealth</p><h2>Connect the firm<br><em>to the advisor '
          'experience.</em></h2><p>My role brings together brand strategy, marketing team '
          'leadership, recruiting strategy and implementation, and individual advisor '
          'support.</p><p>Working at both levels keeps me close to the leadership decisions and '
          'the people who experience them.</p><a class="text-action" '
          'href="{{peer:/selected-work/coastal-wealth/}}">Read the scope at Dillon Agency <span '
          'aria-hidden="true">↗</span></a></div><dl class="scope-register"><div><dt>My '
          'responsibility</dt><dd>Help shape direction, lead the marketing work, and support '
          'implementation.</dd></div><div><dt>My perspective</dt><dd>The recruiting story and the '
          'support an advisor experiences need to connect.</dd></div><div><dt>The next '
          'question</dt><dd>Who owns the work between a strategic decision and the person it is '
          'meant to help?</dd></div></dl></section>\n'
          '<section class="engagement-spread"><div><p class="kicker">Founder experience / '
          'FRENDS</p><h2>Make the position<br><em>part of the product.</em></h2><p>As co-founder '
          'and CEO, I helped build a fashion-led headphone brand. The audience shaped the product, '
          'materials, partnerships, and how the brand showed up.</p><a class="text-action" '
          'href="[[about]]">Explore the founder story <span '
          'aria-hidden="true">↗</span></a></div><div><p class="kicker">Founder experience / '
          'OPEN</p><h2>Build around<br><em>a point of view.</em></h2><p>OPEN connected art, '
          'community, and a different expression of beer culture. It reinforced my interest in the '
          'relationship between a brand’s identity and the operating work behind it.</p><p '
          'class="note">FRENDS and OPEN are chapters from Keir’s founder experience. They are not '
          'presented as Dillon Agency client engagements.</p></div></section><section '
          'class="simple-close metal-surface"><h2>What are you<br><em>building '
          'next?</em></h2><div><p>Let’s talk about the decisions and support your firm '
          'needs.</p><a class="button" href="[[contact]]">Connect with Keir</a></div></section>'},
 {'id': 'tools',
  'path': '/tools/',
  'title': 'Advisor tools and downloadable resources | Keir Dillon',
  'description': 'Three interactive tools for financial advisors — positioning, presence, and '
                 'content — that run in your browser, plus the downloadable guides and prompt '
                 'library from Keir Dillon.',
  'body': '<div class="article-head"><h1>Make one useful<br><em>improvement.</em></h1><p '
          'class="intro">Three interactive tools and a library of printable companions. The tools '
          'ask you a few questions and build a result you can copy or download; the library holds '
          'the longer PDF guides and prompts. Everything is free, with no sign-up.</p></div><div '
          'class="tool-list tool-index metal-surface"><a class="tool-row" href="[[brief]]"><h3>The '
          'Positioning Blueprint</h3><p><span class="tool-format">Interactive · 6 questions · '
          'about 10 minutes</span>Answer six questions and get back a client brief and a working '
          'introduction. Start here if your audience or message feels broad.</p><span '
          'class="arrow">↗</span></a><a class="tool-row" href="[[audit]]"><h3>The Sniff '
          'Test</h3><p><span class="tool-format">Interactive · 8 questions · about 5 '
          'minutes</span>Answer eight questions about your public presence and get back a ranked '
          'list of what to fix first. Start here if your presence feels inconsistent.</p><span '
          'class="arrow">↗</span></a><a class="tool-row" href="[[planner]]"><h3>Client-question '
          'planner</h3><p><span class="tool-format">Interactive · 4 questions · about 5 '
          'minutes</span>Give one question your clients ask and get back four weekly content '
          'outlines. Start here if you know whom you serve but get stuck on content.</p><span '
          'class="arrow">↗</span></a></div><section class="section"><p class="note">These tools '
          'organize your thinking. They do not scan private accounts, validate market demand, or '
          'approve marketing. Inputs are processed in your browser and are not sent to Keir. Copy '
          'or download the result before closing the page.</p><p>Prefer to work on paper, or want '
          'the longer version? The <a href="/resources">resource library</a> holds the printable '
          'companions: the three-pass <a href="/resources/positioning-blueprint">Positioning '
          'Blueprint</a>, the <a href="/resources/audit">Sniff Test</a> as four audience-specific '
          'PDFs, and the <a href="/prompts/positioning">positioning prompt '
          'library</a>.</p></section><section class="advisor-bridge"><h2>Supporting '
          'advisors<br><em>across a firm?</em></h2><div><p>These tools are a starting point. My '
          'fractional CMO work connects advisor support with the firm’s brand, team, recruiting '
          'priorities, and delivery.</p><a class="text-action" '
          'href="{{peer:/advisor-marketing/}}">Explore advisor support at Dillon Agency <span '
          'aria-hidden="true">↗</span></a></div></section>'},
 {'id': 'brief',
  'path': '/tools/client-brief/',
  'title': 'The Positioning Blueprint: client brief',
  'description': 'Build a working client-attraction brief and introduction for your '
                 'financial-advisor practice.',
  'body': '<div class="article-head"><p class="kicker">Free tool / Quick start</p><h1>The '
          'Positioning Blueprint.</h1><p class="intro">Start with a client brief you can use to '
          'make better marketing decisions.</p></div><div class="form-grid"><div><form '
          'id="brief-form" data-tool="brief" data-output="brief-result"><label '
          'class="field"><span>Who do you want to work with?</span><input name="audience" required '
          'maxlength="240" placeholder="e.g. business owners"><small>Describe a group you '
          'understand. Leave personal client information out.</small></label><label '
          'class="field"><span>What situation brings them to you?</span><input name="moment" '
          'required maxlength="240" placeholder="e.g. preparing for a possible business '
          'sale"><small>A real trigger, question, or transition.</small></label><label '
          'class="field"><span>What do you help them work through?</span><textarea name="help" '
          'required maxlength="600" placeholder="e.g. organizing personal financial decisions '
          'around the transition"></textarea><small>Use service language, not a promised financial '
          'result.</small></label><label class="field"><span>What is distinctive about your '
          'approach?</span><textarea name="process" required maxlength="600" placeholder="e.g. a '
          'documented first-90-days planning process"></textarea><small>Describe work you actually '
          'perform.</small></label><label class="field"><span>What supports that '
          'explanation?</span><textarea name="proof" required maxlength="600" placeholder="e.g. a '
          'specific process I can demonstrate"></textarea><small>Relevant experience, a documented '
          'process, or other evidence you can substantiate.</small></label><label '
          'class="field"><span>Where can you reach these people?</span><input name="channel" '
          'required maxlength="240" placeholder="e.g. a local business-owner '
          'association"><small>Name an actual community, partner relationship, or place to '
          'investigate.</small></label><div class="actions"><button type="submit">Build my '
          'brief</button><button type="button" class="secondary" data-example="brief-form">Try a '
          'fictional example</button></div><p class="note spacer">This creates an editable draft '
          'from your inputs. No AI account needed. Your answers are not sent or '
          'saved.</p></form><section class="result" id="brief-result" hidden tabindex="-1" '
          'aria-label="Your result"><h2>Your working result</h2><pre '
          'id="brief-result-text"></pre><div class="actions"><button type="button" '
          'data-copy="brief-result-text">Copy result</button><button type="button" '
          'class="secondary" data-download="brief-result-text" '
          'data-filename="client-attraction-brief.txt">Download '
          'result</button></div></section></div><aside><h3>A working direction</h3><p>Your brief '
          'should identify a person, a situation, and a credible reason to consider you.</p><p>Use '
          'it to guide a headline, an introduction, or a conversation with someone in your '
          'audience.</p><h3>Before choosing a niche</h3><p>Check your service capability, access '
          'to the audience, and whether the work fits your practice. A polished sentence is only a '
          'starting hypothesis.</p><a href="[[ideal]]">Read the ideal-client guide '
          '→</a></aside></div>'},
 {'id': 'audit',
  'path': '/tools/presence-check/',
  'title': 'The Sniff Test: advisor presence self-review',
  'description': 'Review whether a prospective client can understand your audience, value, '
                 'evidence, and next step.',
  'body': '<div class="article-head"><p class="kicker">Free tool / Self-review</p><h1>The Sniff '
          'Test.</h1><p class="intro">Look at your public presence through the eyes of someone '
          'deciding whether to speak with you.</p></div><div class="form-grid"><div><form '
          'data-tool="audit" data-output="audit-result"><fieldset class="question"><legend>1. A '
          'reader can identify the client situation I work with.</legend><div '
          'class="choices"><label><input type="radio" name="audience" value="yes" '
          'required>Clear</label><label><input type="radio" name="audience" value="partly" '
          'required>Partly</label><label><input type="radio" name="audience" value="no" '
          'required>Missing</label></div></fieldset><fieldset class="question"><legend>2. My '
          'opening explains the kind of help I provide.</legend><div class="choices"><label><input '
          'type="radio" name="service" value="yes" required>Clear</label><label><input '
          'type="radio" name="service" value="partly" required>Partly</label><label><input '
          'type="radio" name="service" value="no" '
          'required>Missing</label></div></fieldset><fieldset class="question"><legend>3. My '
          'profile and homepage tell a consistent story.</legend><div '
          'class="choices"><label><input type="radio" name="consistency" value="yes" '
          'required>Clear</label><label><input type="radio" name="consistency" value="partly" '
          'required>Partly</label><label><input type="radio" name="consistency" value="no" '
          'required>Missing</label></div></fieldset><fieldset class="question"><legend>4. My role '
          'and firm affiliations are understandable.</legend><div class="choices"><label><input '
          'type="radio" name="affiliation" value="yes" required>Clear</label><label><input '
          'type="radio" name="affiliation" value="partly" required>Partly</label><label><input '
          'type="radio" name="affiliation" value="no" '
          'required>Missing</label></div></fieldset><fieldset class="question"><legend>5. My '
          'claims have evidence I can substantiate and use.</legend><div '
          'class="choices"><label><input type="radio" name="proof" value="yes" '
          'required>Clear</label><label><input type="radio" name="proof" value="partly" '
          'required>Partly</label><label><input type="radio" name="proof" value="no" '
          'required>Missing</label></div></fieldset><fieldset class="question"><legend>6. My '
          'content answers questions my intended clients ask.</legend><div '
          'class="choices"><label><input type="radio" name="questions" value="yes" '
          'required>Clear</label><label><input type="radio" name="questions" value="partly" '
          'required>Partly</label><label><input type="radio" name="questions" value="no" '
          'required>Missing</label></div></fieldset><fieldset class="question"><legend>7. A '
          'visitor can understand what happens in a first conversation.</legend><div '
          'class="choices"><label><input type="radio" name="next" value="yes" '
          'required>Clear</label><label><input type="radio" name="next" value="partly" '
          'required>Partly</label><label><input type="radio" name="next" value="no" '
          'required>Missing</label></div></fieldset><fieldset class="question"><legend>8. My basic '
          'details, links, and professional information are current.</legend><div '
          'class="choices"><label><input type="radio" name="current" value="yes" '
          'required>Clear</label><label><input type="radio" name="current" value="partly" '
          'required>Partly</label><label><input type="radio" name="current" value="no" '
          'required>Missing</label></div></fieldset><button type="submit">See my '
          'priorities</button></form><section class="result" id="audit-result" hidden '
          'tabindex="-1" aria-label="Your result"><h2>Your working result</h2><pre '
          'id="audit-result-text"></pre><div class="actions"><button type="button" '
          'data-copy="audit-result-text">Copy result</button><button type="button" '
          'class="secondary" data-download="audit-result-text" '
          'data-filename="presence-self-review.txt">Download '
          'result</button></div></section></div><aside><h3>Open your site and profile</h3><p>Read '
          'them as they are today. Answer “partly” when you are unsure.</p><p>The result groups '
          'missing and partial items, then gives you up to three improvements in checklist '
          'order.</p><h3>A useful check, not a prediction</h3><p>This is based on your answers. It '
          'does not fetch your website, inspect search results, or calculate a '
          'marketing-performance score.</p><a href="[[referrals]]">What a referred prospect should '
          'find →</a></aside></div>'},
 {'id': 'planner',
  'path': '/tools/content-plan/',
  'title': 'Client-question content planner for financial advisors',
  'description': 'Turn one client question into four useful weekly content outlines.',
  'body': '<div class="article-head"><p class="kicker">Free tool / Content planner</p><h1>One '
          'question.<br><em>Four useful angles.</em></h1><p class="intro">Create a manageable '
          'content plan around something your intended clients actually want to '
          'understand.</p></div><div class="form-grid"><div><form id="content-form" '
          'data-tool="content" data-output="content-result"><label class="field"><span>Who is this '
          'content for?</span><input name="audience" required maxlength="240" placeholder="e.g. '
          'people preparing for retirement"><small>Use the audience from your client '
          'brief.</small></label><label class="field"><span>What question do they '
          'ask?</span><textarea name="question" required maxlength="600" placeholder="e.g. What '
          'happens in a first planning conversation?"></textarea><small>A general question, with '
          'no client-sensitive details.</small></label><label class="field"><span>What is your '
          'accurate starting answer?</span><textarea name="answer" required maxlength="600" '
          'placeholder="e.g. We discuss what prompted the meeting and agree on a useful next '
          'step."></textarea><small>Write a few plain-language facts based on your actual '
          'process.</small></label><label class="field"><span>What useful next step will you '
          'invite?</span><input name="next" required maxlength="240" placeholder="e.g. What would '
          'you want to understand before a first conversation?"><small>Keep it appropriate to the '
          'topic.</small></label><div class="actions"><button type="submit">Build the '
          'outlines</button><button type="button" class="secondary" '
          'data-example="content-form">Try a fictional example</button></div><p class="note '
          'spacer">This is a structured outline tool. You supply the facts and finish the writing. '
          'Your answers are not sent or saved.</p></form><section class="result" '
          'id="content-result" hidden tabindex="-1" aria-label="Your result"><h2>Your working '
          'result</h2><pre id="content-result-text"></pre><div class="actions"><button '
          'type="button" data-copy="content-result-text">Copy result</button><button type="button" '
          'class="secondary" data-download="content-result-text" '
          'data-filename="four-week-content-plan.txt">Download '
          'result</button></div></section></div><aside><h3>Explain. Clarify. Prepare. '
          'Show.</h3><p>Use the same question from four angles, each with a different purpose for '
          'the reader.</p><p>Record one short answer, then use it as the basis for a written post. '
          'A modest routine can give you useful information about what people respond '
          'to.</p><h3>Review before publishing</h3><p>Keep every statement true to your process. '
          'Do not invent client stories or outcomes. Use your firm’s normal review '
          'requirements.</p><a href="[[marketing]]">Build the wider marketing plan '
          '→</a></aside></div>'},
 {'id': 'guides',
  'path': '/guides/',
  'title': 'Financial advisor brand and marketing guides',
  'description': 'Advisor marketing field notes from Keir Dillon. Practical guidance informed by '
                 'the connection between firm-level marketing leadership and advisor support.',
  'body': '<div class="article-head"><h1>The decisions<br>behind the marketing.</h1><p '
          'class="intro">Field notes for financial advisors who want their brand and content to '
          'connect with the clients they want to serve.</p></div><section class="section rule '
          'link-list"><a href="[[ideal]]">How to define your ideal client<small>Start with the '
          'person, the situation, your capability, and access.</small></a><a '
          'href="[[referrals]]">What a referred prospect should find<small>Help your public '
          'presence reinforce why someone introduced you.</small></a><a href="[[marketing]]">A '
          'practical financial-advisor marketing plan<small>Turn a client focus into a channel '
          'choice and a sustainable routine.</small></a></section><section '
          'class="advisor-bridge"><h2>The firm behind<br><em>the individual '
          'practice.</em></h2><div><p>I share these notes alongside my work as a fractional CMO. '
          'For firm leaders, they offer a view into how I approach advisor support as part of the '
          'wider marketing responsibility.</p><a class="text-action" '
          'href="{{peer:/selected-work/coastal-wealth/}}">See the firm-level scope at Dillon '
          'Agency <span aria-hidden="true">↗</span></a></div></section>'},
 {'id': 'ideal',
  'path': '/guides/define-ideal-client/',
  'title': 'How financial advisors can define their ideal client',
  'description': 'A practical way to choose an advisor client focus, pressure-test it, and '
                 'translate it into a brand message.',
  'body': '<div class="article-head"><p class="kicker">Field notes for financial '
          'advisors</p><h1>How to define<br>your ideal client.</h1><p class="intro">Start with a '
          'situation you understand and a service you can deliver well.</p></div><div '
          'class="reading editorial-reading"><p class="byline">By Keir Dillon · September '
          '2026</p><p>A useful ideal-client definition connects four things: the person you want '
          'to serve, the situation that makes your help relevant, your ability to do the work, and '
          'a practical way to reach them. Income or asset levels alone rarely answer all '
          'four.</p><h2>Begin with actual work.</h2><p>Look at several relationships where you did '
          'work you want to repeat. Keep personal details out of your notes. What prompted those '
          'people to seek help? Which decisions did you help them work through? What made the '
          'relationship productive for both sides?</p><p>Separate enjoyment from capability. You '
          'may like working with entrepreneurs, but a particular business transition may require '
          'services, experience, or professional relationships you do not yet have. Your focus '
          'needs to fit what the practice can deliver.</p><h2>Describe the '
          'moment.</h2><p>“Business owners” names a large population. “Business owners preparing '
          'for a possible sale” describes a situation with a clearer set of questions. That does '
          'not automatically make it the right niche. It gives you a more specific hypothesis to '
          'investigate.</p><p>Write the question in the words someone might actually use. For '
          'example: “What would selling the business mean for my family’s finances?” This is an '
          'illustrative client question, not a finding from a client interview.</p><h2>Check '
          'access and fit.</h2><p>Before redesigning your site around that hypothesis, identify '
          'how you could speak with people in the group. An existing professional relationship may '
          'be a more useful starting point than choosing a platform because it is '
          'popular.</p><p>Ask whether the group needs the services you provide, whether your '
          'service model can support the relationship, and whether you have capacity for more of '
          'this work. These questions belong beside the creative work.</p><h2>Test understanding '
          'before polishing.</h2><p>Share a short explanation with a few people who resemble the '
          'intended audience. Ask them what they think you do, when they would consider speaking '
          'with you, and what is unclear. Their ability to explain the offer back to you is more '
          'informative than whether they “like” the wording.</p><p>Also ask what they tried the '
          'last time the problem appeared. That helps distinguish an interesting topic from an '
          'actual reason to act.</p><h2>Make the choice visible.</h2><p>Use the client situation '
          'to shape your homepage introduction, profile, and content questions. You do not need to '
          'claim that no other advisor can do the work. You need a clear, supportable explanation '
          'of why your experience and approach are relevant.</p><p>A focused message does not '
          'automatically require turning away every existing client outside the focus. It '
          'identifies whom the next phase of your marketing is designed to reach.</p><div '
          'class="callout"><h3>Put the idea to work</h3><p>Build a client brief, then mark every '
          'statement as known, assumed, or still to test. Refine the assumptions through real '
          'conversations.</p><a class="button" href="[[brief]]">Build your client '
          'brief</a></div><p class="source-link">Related reading: <a '
          'href="https://www.kitces.com/blog/ideal-client-persona-financial-advisor-niche-marketing-messaging/" '
          'target="_blank" rel="noopener">Kitces on using client personas in advisor '
          'marketing</a>. The process above is an editorial recommendation, not a promise of '
          'client acquisition.</p></div>'},
 {'id': 'referrals',
  'path': '/guides/referral-presence/',
  'title': 'What a referred prospect should find on an advisor website',
  'description': 'Review the introduction, evidence, affiliation, and next step that support a '
                 'financial-advisor referral.',
  'body': '<div class="article-head"><p class="kicker">Field notes for financial '
          'advisors</p><h1>What a referred<br>prospect should find.</h1><p class="intro">Make your '
          'public presence support the reason someone introduced you.</p></div><div class="reading '
          'editorial-reading"><p class="byline">By Keir Dillon · September 2026</p><p>A referral '
          'gives someone a reason to consider a conversation. Your website and profile can help '
          'them understand that reason in more detail. They should be able to tell whom you work '
          'with, how you approach the relevant problem, and what a first conversation '
          'involves.</p><h2>Keep the introduction consistent.</h2><p>Read the first line of your '
          'website and profile side by side. They can use different wording while communicating '
          'the same focus. If one describes business-owner planning and the other gives only a '
          'generic investment message, the visitor has more to reconcile.</p><p>Write one clear '
          'explanation of your role. Keep required firm and affiliation language accurate and '
          'understandable alongside it. Do not remove necessary disclosures to create a tidier '
          'design.</p><h2>Explain the work.</h2><p>Many firms use similar adjectives: personal, '
          'comprehensive, trusted. A concrete description of what happens in the relationship can '
          'be more informative. Explain the early steps, the questions you ask, and how you '
          'coordinate the work you actually provide.</p><p>Use a fictional example when a simple '
          'illustration helps. Label it as fictional. Do not turn an illustrative situation into a '
          'claimed case study or imply a result you have not measured.</p><h2>Give claims a '
          'foundation.</h2><p>Check every credential, experience statement, award, or result for '
          'accuracy and appropriate presentation. Your firm’s review process should determine what '
          'evidence can be used and how. A self-review tool cannot make that determination for '
          'you.</p><p>A useful educational explanation is itself a way for someone to see how you '
          'think. It gives them more to evaluate than a list of services alone.</p><h2>Make the '
          'next step understandable.</h2><p>“Let’s talk” is friendlier when a visitor knows what '
          'the conversation is for. Explain what they can expect, how long it typically takes if '
          'you know, and whether preparation is required. Check that the contact route actually '
          'works.</p><p>Do not create more steps than the relationship needs. A short description '
          'of the first conversation and one clear route to it may be enough.</p><h2>Check the '
          'journey, then ask.</h2><p>Review your name, role, contact details, and links across the '
          'public places you maintain. Look for stale information and confusing '
          'transitions.</p><p>When someone does inquire, ask what they looked at before reaching '
          'out and what helped them understand your work. Treat that as useful feedback, not proof '
          'that a particular website change caused the inquiry.</p><div class="callout"><h3>Find '
          'one thing to improve</h3><p>The Sniff Test helps you review eight parts of your '
          'presence and choose a short list of priorities.</p><a class="button" '
          'href="[[audit]]">Run the self-review</a></div><p class="note">This guide concerns brand '
          'communication. It does not determine regulatory requirements or guarantee that a '
          'prospect will book a meeting.</p></div>'},
 {'id': 'marketing',
  'path': '/guides/financial-advisor-marketing-plan/',
  'title': 'A practical financial advisor marketing plan',
  'description': 'Build a focused marketing plan around a client situation, a message, a channel, '
                 'a routine, and useful measurement.',
  'body': '<div class="article-head"><p class="kicker">Field notes for financial advisors</p><h1>A '
          'marketing plan<br>you can keep running.</h1><p class="intro">Connect the client you '
          'want to attract to the work you can realistically sustain.</p></div><div class="reading '
          'editorial-reading"><p class="byline">By Keir Dillon · September 2026</p><p>A practical '
          'financial-advisor marketing plan needs a defined audience, a clear message, a way to '
          'reach that audience, a repeatable activity, and a way to learn from the response. The '
          'first version can fit on one page.</p><h2>Choose the outcome you can '
          'observe.</h2><p>“Be more visible” is difficult to evaluate on its own. A more useful '
          'initial objective might be to start relevant conversations with people in a defined '
          'client situation or help referred prospects understand a particular service.</p><p>Keep '
          'the time horizon honest. Publishing a few articles can establish useful material; it '
          'does not establish a predictable client-acquisition system.</p><h2>Match a channel to '
          'access.</h2><p>Start with where you can actually reach the people you want to serve. '
          'That may be a professional association, a referral relationship, a small event, a '
          'publication, or a search topic. Research the audience before committing to a '
          'platform.</p><p>Content needs distribution. A strong answer sitting on an unknown '
          'website may need an introduction from a person or organization the audience already '
          'trusts.</p><h2>Build a routine around real questions.</h2><p>Take one question you are '
          'qualified to answer. Explain what someone needs to understand, clarify a common '
          'misunderstanding you have actually encountered, provide a preparation checklist, and '
          'describe your process. Those are four different angles on the same subject.</p><p>The '
          'client-question planner creates outlines for that routine. You supply the facts, write '
          'the finished content, and follow your normal review process.</p><h2>Count time as a '
          'cost.</h2><p>Kitces’ March 2026 analysis of its 2024 advisor-marketing study reports '
          'that advisor and staff time represented 71% of total marketing expenditure in the '
          'study’s 2023 data. It is a useful reminder to measure the effort around the publishing, '
          'not just subscriptions and advertising bills. The finding is not a benchmark for every '
          'advisor channel. <a '
          'href="https://www.kitces.com/blog/marketing-scale-growth-advisory-firm-cost-capacity-crossroads-strategies/" '
          'target="_blank" rel="noopener">Read the Kitces analysis</a>.</p><p>Choose the parts '
          'that need your judgment. Delegate preparation, formatting, and scheduling when '
          'appropriate. Preserve your review of the final work.</p><h2>Use a small set of '
          'measures.</h2><p>Record what you published, the relevant conversations it started, the '
          'inquiries that matched your chosen client situation, and the time you spent. Ask new '
          'contacts how they found you and what they read or watched.</p><p>If activity is '
          'consistent but response is weak, look at distribution and relevance. If response is '
          'good but the workload is unsustainable, simplify production. Do not assume the only '
          'answer is to publish more.</p><h2>Write the one-page plan.</h2><ol><li>The client '
          'situation I want to reach.</li><li>The service and approach I want people to '
          'understand.</li><li>The place or relationship through which I can reach '
          'them.</li><li>One question I will answer this month.</li><li>The time I will allocate '
          'and who owns each task.</li><li>The evidence I will review before changing the '
          'plan.</li></ol><div class="callout"><h3>Start with next month’s content</h3><p>Choose '
          'one audience question and build four practical outlines around it.</p><a class="button" '
          'href="[[planner]]">Open the content planner</a></div></div>'},
 {'id': 'about',
  'path': '/about/',
  'title': 'Keir Dillon: athlete, founder, fractional CMO',
  'description': 'From professional snowboarding and FRENDS to fractional CMO leadership in '
                 'financial services. The experience behind Keir Dillon’s approach.',
  'body': '<section class="story-opening"><p class="kicker">Keir Dillon / The story</p><h1>A '
          'different route.<br><em>A distinct point of view.</em></h1><div '
          'class="story-opening-bottom"><p>From the mountains to live television, consumer brands, '
          'and financial services. Each chapter changed the work. Each one sharpened how I see '
          'it.</p><span>Athlete → Broadcaster → Founder → CMO</span></div></section>\n'
          '<section class="story-front"><figure class="photo triptych"><img '
          'src="{{asset:keir-triptych}}" alt="Three candid frames of Keir Dillon talking and '
          'laughing in a café" loading="eager" decoding="async" '
          'fetchpriority="high"><figcaption>Keir Dillon / From the personal '
          'archive</figcaption></figure><div class="story-intro"><p class="margin-note">Where it '
          'began</p><h2>I learned to build<br><em>by being part of something.</em></h2><p>Growing '
          'up in the Poconos, snowboarding gave me more than a career. It gave me a community, an '
          'eye for style, and a habit of learning by doing. I became interested in what makes '
          'people care about a person, a product, or an idea.</p></div></section>\n'
          '<section class="chapter athlete-chapter"><div class="chapter-copy"><p '
          'class="kicker">The athlete</p><h2>Find your line.<br><em>Make it your '
          'own.</em></h2><p>I spent two decades in professional snowboarding, competing at the X '
          'Games and winning three World Superpipe championships. Riding for brands including '
          'Burton, Nike, and Pepsi gave me a close view of how performance and identity '
          'connect.</p><p>Being part of the FRENDS crew taught me something just as valuable: a '
          'shared point of view can bring people together long before anyone calls it a '
          'brand.</p><p class="chapter-lesson">What stays with me: the details matter, and people '
          'can feel when something is true to its culture.</p></div><div '
          'class="athlete-archive"><figure class="photo snow-action"><img '
          'src="{{asset:snow-park}}" alt="Keir Dillon airborne above the halfpipe in Park City" '
          'loading="lazy" decoding="async"><figcaption>Park City / Photo: '
          'Moran</figcaption></figure><figure class="photo magazine"><img '
          'src="{{asset:snow-cover}}" alt="Keir Dillon featured on the cover of Onboard '
          'snowboarding magazine" loading="lazy" decoding="async"><figcaption>Onboard / Archive '
          'cover</figcaption></figure></div></section>\n'
          '<section class="chapter broadcast-chapter"><div class="broadcast-archive"><figure '
          'class="photo broadcast-main"><img src="{{asset:espn-summer}}" alt="Keir Dillon '
          'interviewing Shaun White as an ESPN X Games sideline reporter" loading="lazy" '
          'decoding="async"><figcaption>ESPN Summer X Games / Broadcast archive '
          'still</figcaption></figure><figure class="photo broadcast-secondary"><img '
          'src="{{asset:espn-winter}}" alt="Keir Dillon and Sal Masekela presenting a Winter X '
          'Games recap" loading="lazy" decoding="async"><figcaption>Winter X Games with Sal '
          'Masekela / Archive still</figcaption></figure></div><div class="chapter-copy"><p '
          'class="kicker">The broadcaster</p><h2>Make the story<br><em>mean '
          'something.</em></h2><p>Moving into television with ESPN and Fuel TV changed my job. I '
          'had to take something I understood deeply and make it matter to someone watching from '
          'home.</p><p>Live broadcasting teaches you to listen, find the point, and communicate it '
          'clearly. Those instincts are part of how I help leaders and advisors explain work that '
          'can otherwise feel complicated or interchangeable.</p><p class="chapter-lesson">What '
          'stays with me: know the audience well enough to know what needs '
          'explaining.</p></div></section>\n'
          '<section class="frends-chapter"><div class="section-heading"><div><p class="kicker">The '
          'founder / FRENDS</p><h2>Build for the person.<br><em>Then build the '
          'company.</em></h2></div><p>As co-founder and CEO of FRENDS, I helped turn an idea about '
          'personal style into a consumer brand, a retail business, and a team.</p></div><div '
          'class="fashion-pair"><figure class="photo fashion-portrait"><img '
          'src="{{asset:frends-fashion}}" alt="FRENDS fashion photography featuring iridescent '
          'headphones" loading="lazy" decoding="async"><figcaption>FRENDS / Fashion and product '
          'photography</figcaption></figure><figure class="photo fashion-runway"><img '
          'src="{{asset:frends-runway}}" alt="Runway photograph of jewel-encrusted headphones from '
          'the FRENDS and Dolce &amp; Gabbana archive" loading="lazy" '
          'decoding="async"><figcaption>FRENDS × Dolce &amp; Gabbana / Collaboration '
          'archive</figcaption></figure></div><div class="founder-detail"><h3>A position has '
          'to<br>survive the real world.</h3><div><p>Our headphones treated design and '
          'self-expression as part of the product. The brand reached retailers including Apple, '
          'Best Buy, and Nordstrom, and collaborated with fashion partners including Dolce &amp; '
          'Gabbana.</p><p>Building the business meant raising capital, developing products, '
          'working with retail partners, and showing up for the decisions after launch. We also '
          'brought FRENDS to Shark Tank.</p><p class="chapter-lesson">What stays with me: the '
          'message, the experience, and the business have to support each '
          'other.</p></div></div><figure class="photo shark-archive"><img '
          'src="{{asset:shark-tank}}" alt="Keir Dillon and his co-presenter presenting FRENDS '
          'headphones on Shark Tank" loading="lazy" decoding="async"><figcaption>FRENDS on Shark '
          'Tank / Archive still</figcaption></figure></section>\n'
          '<section class="open-chapter"><div class="chapter-copy"><p class="kicker">The builder / '
          'OPEN</p><h2>Culture belongs<br><em>in the business.</em></h2><p>With OPEN, I built an '
          'LA beer brand around art, community, and a different expression of beer culture. The '
          'identity had to travel from the can to the places and people around it.</p><p>That '
          'chapter reinforced the connection between a strong brand and the operating work that '
          'makes it available, consistent, and worth coming back to.</p></div><div '
          'class="open-product metal-surface"><figure class="photo contain"><img '
          'src="{{asset:open-cans}}" alt="Three OPEN beer cans with distinct art-led packaging" '
          'loading="lazy" decoding="async"><figcaption>OPEN / Brand and packaging '
          'archive</figcaption></figure></div></section>\n'
          '<section class="today-chapter"><div><figure class="photo today-portrait"><img '
          'src="{{asset:keir-current}}" alt="Keir Dillon, brand strategist and founder of Dillon '
          'Agency" loading="lazy" decoding="async"><figcaption>Keir Dillon / Dillon '
          'Agency</figcaption></figure></div><div class="chapter-copy"><p class="kicker">The work '
          'today</p><h2>Lead the marketing.<br><em>Stay close to the people.</em></h2><p>Today, I '
          'work as a fractional CMO in financial services through Dillon Agency. I partner with '
          'firm leaders on brand strategy, marketing team leadership, recruiting, and '
          'implementation.</p><p>At Coastal Wealth, that includes both the firm-level work and '
          'helping individual advisors with their brands and marketing presence.</p><p>That '
          'connection matters to me. Working with advisors keeps the strategy close to the people '
          'using it. Leading at the firm level creates an opportunity to make useful support more '
          'consistent.</p><p>I also share practical advisor resources, field notes, and Google '
          'Yourself. The Operator’s Room is a community concept taking shape around that '
          'work.</p><a class="text-action" href="{{peer:/selected-work/coastal-wealth/}}">See the '
          'firm scope at Dillon Agency <span aria-hidden="true">↗</span></a></div></section>'},
 {'id': 'room',
  'path': '/the-operators-room/',
  'title': 'The Operator’s Room: an advisor community in development',
  'description': 'The Operator’s Room: a learning community in development for financial advisors '
                 'who want a more recognizable practice. See what it covers, and use the free '
                 'advisor tools available now.',
  'body': '<section class="room-opening"><p class="kicker">The Operator’s Room</p><h1>Good work '
          'gets better<br><em>in good company.</em></h1><p class="intro">A learning community for '
          'financial advisors who want a more recognizable practice: somewhere to bring a real '
          'question and leave with something you can use. It is in development now, and the '
          'questions advisors send me are shaping what it covers.</p></section><figure '
          'class="photo community-photo"><img src="{{asset:advisor-community}}" alt="Illustrative '
          'scene of four advisors sharing ideas around a studio meeting table" loading="eager" '
          'decoding="async" fetchpriority="high"><figcaption>The kind of working conversation it '
          'is designed around. Illustrative image.</figcaption></figure><section '
          'class="room-body"><div><h2>Bring a question.<br><em>Leave with something '
          'useful.</em></h2><p>How do I explain what makes my practice relevant? What should my '
          'website say? How do I create useful content without turning it into another full-time '
          'job?</p><p>Those are the questions I want us to work through together, using real '
          'examples, practical tools, and thoughtful feedback. They also inform the advisor '
          'support I help firms develop through my fractional CMO work.</p></div><div '
          'class="room-agenda"><h3>The work on the table</h3><p>Client focus and '
          'positioning</p><p>Brand, website, and profile clarity</p><p>A content routine you can '
          'sustain</p><p>Practical AI with human judgment</p></div></section><section '
          'class="simple-close metal-surface"><h2>Send me the question<br><em>you are sitting '
          'on.</em></h2><div><p>It will help shape what the Room covers, and I will answer it '
          'either way. In the meantime the free <a href="[[tools]]">advisor tools</a> cover '
          'positioning, presence, and a content plan you can start this week.</p><a class="button" '
          'href="mailto:keir@dillonagency.co?subject=A%20question%20for%20The%20Operator%E2%80%99s%20Room">Email '
          'Keir</a><a class="text-action" href="https://linkedin.com/in/keirdillon" '
          'target="_blank" rel="noopener">Follow the work on LinkedIn <span '
          'aria-hidden="true">↗</span></a></div></section><p class="note room-expectation">An '
          'independent learning community. Participation will not be permission for recruiting or '
          'vendor outreach. Keep client details private and use your firm’s normal review '
          'process.</p>'},
 {'id': 'contact',
  'path': '/contact/',
  'title': 'Contact Keir Dillon',
  'description': 'Contact Keir Dillon about fractional CMO work, advisor marketing, partnerships, '
                 'speaking, or an idea worth exploring.',
  'body': '<section class="contact-opening"><div><p class="kicker">Keir Dillon / Contact</p><h1>A '
          'useful conversation<br><em>starts with your context.</em></h1><p class="intro">Tell me '
          'what you’re building, where the work is getting stuck, and what you want to '
          'change.</p></div><div class="contact-panel metal-surface"><h2>Let’s talk.</h2><p>Send '
          'Keir a note. We can start with the question and work out the right next step.</p><a '
          'class="button" '
          'href="mailto:keir@dillonagency.co?subject=A%20conversation%20with%20Keir%20Dillon">Email '
          'Keir</a><p class="email-address" id="contact-email">keir@dillonagency.co</p><button '
          'class="secondary" type="button" data-copy="contact-email">Copy email address</button><p '
          'class="note spacer">Opens your email app. You can also copy the address into your usual '
          'email service.</p><a class="text-action" href="https://linkedin.com/in/keirdillon" '
          'target="_blank" rel="noopener">Connect on LinkedIn <span '
          'aria-hidden="true">↗</span></a></div></section><section class="advisor-bridge"><h2>A '
          'little context<br><em>goes a long way.</em></h2><div><p>Include your role and firm, the '
          'priority you’re working on, who is involved today, and any timing that matters. A short '
          'note is enough to begin.</p><p>For partnerships, speaking, or an advisor question, tell '
          'me what you have in mind.</p></div></section>'}]
