'use strict';
function notify(message){const el=document.getElementById('notice');el.textContent=message;el.hidden=false;clearTimeout(window.noticeTimer);window.noticeTimer=setTimeout(()=>el.hidden=true,3000);}
function downloadText(name,text){const blob=new Blob([text],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function copyText(text){try{await navigator.clipboard.writeText(text);notify('Copied.');}catch(e){const t=document.createElement('textarea');t.value=text;t.style.position='fixed';t.style.opacity='0';document.body.append(t);t.select();let ok=false;try{ok=document.execCommand('copy');}catch(e){}t.remove();notify(ok?'Copied.':'Copy is unavailable here. Use Download or select the result text.');}}
document.querySelectorAll('form[data-tool]').forEach(form=>form.addEventListener('submit',event=>{event.preventDefault();const data=Object.fromEntries(new FormData(form));const output=document.getElementById(form.dataset.output);try{const result=form.dataset.tool==='audit'?KDTools.audit(KDTools.checks.map(c=>data[c[0]])):KDTools[form.dataset.tool](data);output.querySelector('pre').textContent=result;output.hidden=false;output.focus();}catch(e){notify(e.message);}}));
document.querySelectorAll('[data-copy]').forEach(b=>b.addEventListener('click',()=>copyText(document.getElementById(b.dataset.copy).innerText)));
document.querySelectorAll('[data-download]').forEach(b=>b.addEventListener('click',()=>downloadText(b.dataset.filename||'keir-dillon-notes.txt',document.getElementById(b.dataset.download).innerText)));
document.querySelectorAll('[data-example]').forEach(b=>b.addEventListener('click',()=>{const form=document.getElementById(b.dataset.example);const examples={brief:{audience:'business owners',moment:'preparing for a possible sale of their company',help:'organizing the personal financial questions around the transition',process:'mapping the decisions with the owner and their existing professional team',proof:'a documented planning process and relevant experience that I can explain accurately',channel:'an existing relationship with a local business-owner association'},content:{audience:'people preparing for retirement',question:'What happens in a first planning conversation?',answer:'We discuss what prompted the meeting, explain how our practice works, and agree on a useful next step.',next:'What would you want to understand before a first conversation?'}};Object.entries(examples[form.dataset.tool]||{}).forEach(([k,v])=>form.elements[k].value=v);notify('Fictional example loaded. Replace it with your own details.');}));
document.querySelectorAll('[data-toggle-menu]').forEach(b=>b.addEventListener('click',()=>{const menu=document.getElementById('menu');const open=b.getAttribute('aria-expanded')==='true';b.setAttribute('aria-expanded',String(!open));menu.classList.toggle('open',!open);}));
if(document.body.dataset.mode==='single'){
 const pages=[...document.querySelectorAll('[data-page]')];
 function route(){const key=location.hash.slice(1)||'home';if(key==='main'){const active=pages.find(p=>!p.hidden);if(active)active.focus();return;}const page=pages.find(p=>p.dataset.page===key)||pages[0];pages.forEach(p=>p.hidden=p!==page);document.title=page.dataset.title+(page.dataset.title.includes(document.body.dataset.brand)?'':' | '+document.body.dataset.brand);document.querySelectorAll('[data-nav]').forEach(a=>a.setAttribute('aria-current',a.dataset.nav===page.dataset.page?'page':'false'));window.scrollTo(0,0);document.getElementById('menu').classList.remove('open');document.querySelector('[data-toggle-menu]').setAttribute('aria-expanded','false');page.focus({preventScroll:true});}
 window.addEventListener('hashchange',route);route();
}
